config/routes.rb
DeviseApp::Application.routes.draw do


  use_doorkeeper

  get "welcome/index"
  root :to => 'welcome#index'


  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :tasks
      resources :listings
      match 'user', to: 'users#show'
    end
  end

  resources :listing_photos



  devise_for :users,
            :path_names => { :sign_in => 'login',
                              :sign_out => 'logout',
                              :password => 'secret',
                              :confirmation => 'verification',
                              :unlock => 'unblock',
                              :registration => 'register',
                              :sign_up => 'cmon_let_me_in' }


end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  attr_accessible :name, :owner
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :tasks
  has_many :listings
end

app/controllers/api/v1/base_controller.rb
module Api
  module V1
    class BaseController < ApplicationController


      # Avoid CSRF error
      # http://blog.dougpetkanics.com/making-a-post-request-to-a-rails-api-endpoint/
      # http://stackoverflow.com/questions/9362910/rails-warning-cant-verify-csrf-token-authenticity-for-json-devise-requests
      skip_before_filter :verify_authenticity_token #, :if => Proc.new { |c| c.request.format == 'application/json' }

      doorkeeper_for :all
      #before_filter :authenticate_user!

      private
        def current_user
          if doorkeeper_token
            @current_user ||= User.find(doorkeeper_token.resource_owner_id)
          end
        end
    end
  end
end

app/controllers/api/v1/tasks_controller.rb
module Api
  module V1
    class TasksController < BaseController



      # GET /tasks
      # GET /tasks.json
      def index

        # @tasks = Task.all
        # BMR -- only get for currently logged-in user

        #user = User.find(doorkeeper_token.resource_owner_id)
        #@tasks = current_user.tasks
        @tasks = Task.find_all_by_user_id( current_user.id )

        respond_to do |format|
          format.json { render json: @tasks }
        end
      end

      # GET /tasks/1
      # GET /tasks/1.json
      def show
        # @task = Task.find(params[:id])
       	# BMR -- update to only pull for currently logged-in user
        @task = Task.where(id: params[:id]).where( user_id:  current_user.id )

        respond_to do |format|
          format.json { render json: @task }
        end
      end

      # POST /tasks
      # POST /tasks.json
      def create

        # http://stackoverflow.com/questions/18690196/how-should-i-format-a-json-post-request-to-my-rails-app
        @task = Task.new(params[:task])

        # BMR
        @task.user_id = current_user.id

        respond_to do |format|
          if @task.save
            format.json { render json: @task }
          else
            format.json { render json: @task.errors, status: :unprocessable_entity }
          end
        end

      end


      # PUT /tasks/1
      # PUT /tasks/1.json
      def update
        #@task = Task.find(params[:id])
       	# BMR -- update to only pull for currently logged-in user
        @task = Task.where(id: params[:id]).where( user_id:  current_user.id )

        respond_to do |format|
          if @task.update_attributes(params[:task])
            format.json { head :no_content }
          else
            format.json { render json: @task.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /tasks/1
      # DELETE /tasks/1.json
      def destroy
        begin

          @task = Task.find(params[:id])
          response_msg = :no_content
          if ( @task.user_id == current_user.id )
            @task.destroy
            response_msg = "Delete successful"
          else
            response_msg = "Current user is not authorized to delete this item"
          end

    	rescue ActiveRecord::RecordNotFound
            response_msg = "No item by that id"
        end


        respond_to do |format|
          format.json { render json: response_msg }
        end
     end


    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < BaseController
      doorkeeper_for :all
      respond_to :json
 
      def show
        respond_with current_user.as_json(only: [:email, :current_sign_in_at])
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listing_photos_helper.rb
module ListingPhotosHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>

<%= yield %>

  <%= debug(current_user) if user_signed_in? %>

</body>
</html>

app/views/listing_photos/_form.html.erb
<%= form_for @listing_photo, :html => {:multipart => true} do |f| %>
  <% if @listing_photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing_photo.errors.count, "error") %> prohibited this listing_photo from being saved:</h2>

      <ul>
      <% @listing_photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <p>
      <%= f.label :caption %>
      <%= f.text_field :caption %>
    </p>
    <p>
      <%= f.label :listing_id %>
      <%= f.select(:listing_id, options_for_select([['2008 Honda Fit', 28]])) %>
    </p>
    <p>
      <%= f.file_field :image %>
    </p>
    <%= f.submit %>
  </div>
<% end %>

app/views/listing_photos/edit.html.erb
<h1>Editing listing_photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing_photo %> |
<%= link_to 'Back', listing_photos_path %>

app/views/listing_photos/index.html.erb
<h1>Listing listing_photos</h1>

<table>
  <tr>
    <th>caption</th>
    <th>listing id</th>
    <th>image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @listing_photos.each do |listing_photo| %>
  <tr>
    <td><%= listing_photo.caption %></td>
    <td><%= listing_photo.listing_id %></td>
    <td><%= image_tag listing_photo.image_url(:thumb).to_s %></td>
    <td><%= link_to 'Show', listing_photo %></td>
    <td><%= link_to 'Edit', edit_listing_photo_path(listing_photo) %></td>
    <td><%= link_to 'Destroy', listing_photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Listing photo', new_listing_photo_path %>

app/views/listing_photos/new.html.erb
<h1>New listing_photo</h1>

<%= render 'form' %>

<%= link_to 'Back', listing_photos_path %>

app/views/listing_photos/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Caption:</b>
  <%= @listing_photo.caption %>
</p>
<p>
<%= image_tag @listing_photo.image_url(:large).to_s %>
</p>

<%= link_to 'Edit', edit_listing_photo_path(@listing_photo) %> |
<%= link_to 'Back', listing_photos_path %>

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h1>Listing listings</h1>

<table>
  <tr>
    <th>Title</th>
    <th>End date</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @listings.each do |listing| %>
  <tr>
    <td><%= listing.title %></td>
    <td><%= listing.end_date %></td>
    <td><%= listing.user %></td>
    <td><%= link_to 'Show', listing %></td>
    <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
    <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @listing.title %>
</p>

<p>
  <b>End date:</b>
  <%= @listing.end_date %>
</p>

<p>
  <b>User:</b>
  <%= @listing.user %>
</p>


<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :owner %><br />
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Owner</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.owner %></td>
    <td><%= task.user.email %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Owner:</b>
  <%= @task.owner %>
</p>

<p>
  <b>User:</b>
  <%= @task.user %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to 'Task API', api_v1_tasks_path %>